import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";


export const metadata: Metadata = {
  title: {
    default: "Next.js | Code", 
    template: "%s | Code" 
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body>

        <Header />

        <div className="m-10">
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
